import { jsPDF } from "jspdf";
import { stripCitations } from "@/components/copilot/PrimarySourceLink";

export type ExportSource = {
  id: string;
  name: string;
  type: string;
  rowsUsed: number;
  rowsTotal?: number;
  truncated: boolean;
};

export type ExportTurn = {
  question: string;
  answer: string;
  sources: ExportSource[];
};

/** Extract [..] citation markers so we can list them under the answer. */
function extractCitations(answer: string): string[] {
  const re = /\[([^\]]+)\]/g;
  const seen = new Set<string>();
  const out: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(answer)) !== null) {
    // Skip markdown links like [text](url)
    if (answer[m.index + m[0].length] === "(") continue;
    const raw = m[1].trim();
    if (!raw || seen.has(raw)) continue;
    seen.add(raw);
    out.push(raw);
  }
  return out;
}

function sanitize(text: string): string {
  // jsPDF's Helvetica only supports WinAnsi; drop unsupported chars.
  return text
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/[\u2022]/g, "*")
    .replace(/[^\x09\x0A\x20-\x7E\xA0-\xFF]/g, "");
}

export function exportCopilotTurnToPdf(turn: ExportTurn): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureRoom = (needed: number) => {
    if (y + needed > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const drawLines = (text: string, size: number, opts: { bold?: boolean; color?: [number, number, number] } = {}) => {
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(size);
    const [r, g, b] = opts.color ?? [30, 30, 30];
    doc.setTextColor(r, g, b);
    const lines = doc.splitTextToSize(sanitize(text), maxWidth) as string[];
    const lineHeight = size * 1.35;
    for (const line of lines) {
      ensureRoom(lineHeight);
      doc.text(line, margin, y);
      y += lineHeight;
    }
  };

  const hr = () => {
    ensureRoom(12);
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, y, pageWidth - margin, y);
    y += 12;
  };

  // Header
  drawLines("Copilot answer", 18, { bold: true });
  drawLines(new Date().toLocaleString(), 9, { color: [120, 120, 120] });
  y += 6;
  hr();

  // Question
  drawLines("Question", 11, { bold: true, color: [90, 90, 90] });
  drawLines(turn.question, 12);
  y += 6;

  // Answer (strip citation markers & basic markdown)
  drawLines("Answer", 11, { bold: true, color: [90, 90, 90] });
  const cleanAnswer = stripCitations(turn.answer)
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1");
  drawLines(cleanAnswer, 11);
  y += 8;
  hr();

  // Inline citations
  const citations = extractCitations(turn.answer);
  if (citations.length > 0) {
    drawLines("Inline citations", 11, { bold: true, color: [90, 90, 90] });
    for (const c of citations) drawLines(`  [${c}]`, 10, { color: [60, 60, 60] });
    y += 6;
  }

  // Sources
  drawLines("Cited sources", 11, { bold: true, color: [90, 90, 90] });
  if (turn.sources.length === 0) {
    drawLines("(no sources attached)", 10, { color: [140, 140, 140] });
  } else {
    for (const s of turn.sources) {
      const matched = s.rowsUsed > 0
        ? `${s.rowsUsed}${s.truncated ? "+" : ""} matched row${s.rowsUsed === 1 ? "" : "s"}`
        : `${(s.rowsTotal ?? 0).toLocaleString()} scoped rows · 0 matched`;
      drawLines(`- ${s.name}`, 11, { bold: true });
      drawLines(`    ${s.type} · ${matched}`, 9, { color: [110, 110, 110] });
    }
  }

  // Footer on every page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Copilot · Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 20,
      { align: "center" },
    );
  }

  const slug = (turn.question || "copilot-answer")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "copilot-answer";
  doc.save(`${slug}.pdf`);
}
