/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedSheetsRouteImport } from './routes/_authenticated/sheets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyActivitiesRouteImport } from './routes/_authenticated/my-activities'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedConcernsRouteImport } from './routes/_authenticated/concerns'
import { Route as AuthenticatedBriefingsRouteImport } from './routes/_authenticated/briefings'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedAlertsIndexRouteImport } from './routes/_authenticated/alerts.index'
import { Route as AuthenticatedAgentIndexRouteImport } from './routes/_authenticated/agent.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedSheetsSheetIdRouteImport } from './routes/_authenticated/sheets.$sheetId'
import { Route as AuthenticatedAlertsIdRouteImport } from './routes/_authenticated/alerts.$id'
import { Route as AuthenticatedAgentInboxRouteImport } from './routes/_authenticated/agent.inbox'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSmartAlertsRouteImport } from './routes/_authenticated/admin.smart-alerts'
import { Route as AuthenticatedAdminEmailGroupsRouteImport } from './routes/_authenticated/admin.email-groups'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksWeeklyReportRouteImport } from './routes/api/public/hooks/weekly-report'
import { Route as ApiPublicHooksWeeklyBriefingRouteImport } from './routes/api/public/hooks/weekly-briefing'
import { Route as ApiPublicHooksSmartAlertsScanRouteImport } from './routes/api/public/hooks/smart-alerts-scan'
import { Route as ApiPublicHooksEscalateRouteImport } from './routes/api/public/hooks/escalate'
import { Route as ApiPublicHooksConcernNudgesRouteImport } from './routes/api/public/hooks/concern-nudges'
import { Route as ApiPublicHooksAgentWatchersRouteImport } from './routes/api/public/hooks/agent-watchers'
import { Route as AuthenticatedAgentStageKeyRouteImport } from './routes/_authenticated/agent.stage.$key'
import { Route as AuthenticatedAgentRowKeyRouteImport } from './routes/_authenticated/agent.row.$key'
import { Route as AuthenticatedAgentProjectProjectIdRouteImport } from './routes/_authenticated/agent.project.$projectId'
import { Route as AuthenticatedAgentPersonKeyRouteImport } from './routes/_authenticated/agent.person.$key'
import { Route as AuthenticatedAgentKpiIdRouteImport } from './routes/_authenticated/agent.kpi.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSheetsRoute = AuthenticatedSheetsRouteImport.update({
  id: '/sheets',
  path: '/sheets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyActivitiesRoute =
  AuthenticatedMyActivitiesRouteImport.update({
    id: '/my-activities',
    path: '/my-activities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConcernsRoute = AuthenticatedConcernsRouteImport.update({
  id: '/concerns',
  path: '/concerns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBriefingsRoute = AuthenticatedBriefingsRouteImport.update({
  id: '/briefings',
  path: '/briefings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsIndexRoute =
  AuthenticatedAlertsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAlertsRoute,
  } as any)
const AuthenticatedAgentIndexRoute = AuthenticatedAgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAgentRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSheetsSheetIdRoute =
  AuthenticatedSheetsSheetIdRouteImport.update({
    id: '/$sheetId',
    path: '/$sheetId',
    getParentRoute: () => AuthenticatedSheetsRoute,
  } as any)
const AuthenticatedAlertsIdRoute = AuthenticatedAlertsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAlertsRoute,
} as any)
const AuthenticatedAgentInboxRoute = AuthenticatedAgentInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAgentRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSmartAlertsRoute =
  AuthenticatedAdminSmartAlertsRouteImport.update({
    id: '/admin/smart-alerts',
    path: '/admin/smart-alerts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEmailGroupsRoute =
  AuthenticatedAdminEmailGroupsRouteImport.update({
    id: '/admin/email-groups',
    path: '/admin/email-groups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyReportRoute =
  ApiPublicHooksWeeklyReportRouteImport.update({
    id: '/api/public/hooks/weekly-report',
    path: '/api/public/hooks/weekly-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyBriefingRoute =
  ApiPublicHooksWeeklyBriefingRouteImport.update({
    id: '/api/public/hooks/weekly-briefing',
    path: '/api/public/hooks/weekly-briefing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSmartAlertsScanRoute =
  ApiPublicHooksSmartAlertsScanRouteImport.update({
    id: '/api/public/hooks/smart-alerts-scan',
    path: '/api/public/hooks/smart-alerts-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEscalateRoute = ApiPublicHooksEscalateRouteImport.update({
  id: '/api/public/hooks/escalate',
  path: '/api/public/hooks/escalate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksConcernNudgesRoute =
  ApiPublicHooksConcernNudgesRouteImport.update({
    id: '/api/public/hooks/concern-nudges',
    path: '/api/public/hooks/concern-nudges',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentWatchersRoute =
  ApiPublicHooksAgentWatchersRouteImport.update({
    id: '/api/public/hooks/agent-watchers',
    path: '/api/public/hooks/agent-watchers',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAgentStageKeyRoute =
  AuthenticatedAgentStageKeyRouteImport.update({
    id: '/stage/$key',
    path: '/stage/$key',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentRowKeyRoute =
  AuthenticatedAgentRowKeyRouteImport.update({
    id: '/row/$key',
    path: '/row/$key',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentProjectProjectIdRoute =
  AuthenticatedAgentProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentPersonKeyRoute =
  AuthenticatedAgentPersonKeyRouteImport.update({
    id: '/person/$key',
    path: '/person/$key',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentKpiIdRoute = AuthenticatedAgentKpiIdRouteImport.update({
  id: '/kpi/$id',
  path: '/kpi/$id',
  getParentRoute: () => AuthenticatedAgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agent': typeof AuthenticatedAgentRouteWithChildren
  '/alerts': typeof AuthenticatedAlertsRouteWithChildren
  '/briefings': typeof AuthenticatedBriefingsRoute
  '/concerns': typeof AuthenticatedConcernsRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/my-activities': typeof AuthenticatedMyActivitiesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheets': typeof AuthenticatedSheetsRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/email-groups': typeof AuthenticatedAdminEmailGroupsRoute
  '/admin/smart-alerts': typeof AuthenticatedAdminSmartAlertsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/agent/inbox': typeof AuthenticatedAgentInboxRoute
  '/alerts/$id': typeof AuthenticatedAlertsIdRoute
  '/sheets/$sheetId': typeof AuthenticatedSheetsSheetIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/agent/': typeof AuthenticatedAgentIndexRoute
  '/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/agent/kpi/$id': typeof AuthenticatedAgentKpiIdRoute
  '/agent/person/$key': typeof AuthenticatedAgentPersonKeyRoute
  '/agent/project/$projectId': typeof AuthenticatedAgentProjectProjectIdRoute
  '/agent/row/$key': typeof AuthenticatedAgentRowKeyRoute
  '/agent/stage/$key': typeof AuthenticatedAgentStageKeyRoute
  '/api/public/hooks/agent-watchers': typeof ApiPublicHooksAgentWatchersRoute
  '/api/public/hooks/concern-nudges': typeof ApiPublicHooksConcernNudgesRoute
  '/api/public/hooks/escalate': typeof ApiPublicHooksEscalateRoute
  '/api/public/hooks/smart-alerts-scan': typeof ApiPublicHooksSmartAlertsScanRoute
  '/api/public/hooks/weekly-briefing': typeof ApiPublicHooksWeeklyBriefingRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/briefings': typeof AuthenticatedBriefingsRoute
  '/concerns': typeof AuthenticatedConcernsRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/my-activities': typeof AuthenticatedMyActivitiesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheets': typeof AuthenticatedSheetsRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/email-groups': typeof AuthenticatedAdminEmailGroupsRoute
  '/admin/smart-alerts': typeof AuthenticatedAdminSmartAlertsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/agent/inbox': typeof AuthenticatedAgentInboxRoute
  '/alerts/$id': typeof AuthenticatedAlertsIdRoute
  '/sheets/$sheetId': typeof AuthenticatedSheetsSheetIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/agent': typeof AuthenticatedAgentIndexRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/agent/kpi/$id': typeof AuthenticatedAgentKpiIdRoute
  '/agent/person/$key': typeof AuthenticatedAgentPersonKeyRoute
  '/agent/project/$projectId': typeof AuthenticatedAgentProjectProjectIdRoute
  '/agent/row/$key': typeof AuthenticatedAgentRowKeyRoute
  '/agent/stage/$key': typeof AuthenticatedAgentStageKeyRoute
  '/api/public/hooks/agent-watchers': typeof ApiPublicHooksAgentWatchersRoute
  '/api/public/hooks/concern-nudges': typeof ApiPublicHooksConcernNudgesRoute
  '/api/public/hooks/escalate': typeof ApiPublicHooksEscalateRoute
  '/api/public/hooks/smart-alerts-scan': typeof ApiPublicHooksSmartAlertsScanRoute
  '/api/public/hooks/weekly-briefing': typeof ApiPublicHooksWeeklyBriefingRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRouteWithChildren
  '/_authenticated/alerts': typeof AuthenticatedAlertsRouteWithChildren
  '/_authenticated/briefings': typeof AuthenticatedBriefingsRoute
  '/_authenticated/concerns': typeof AuthenticatedConcernsRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/my-activities': typeof AuthenticatedMyActivitiesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sheets': typeof AuthenticatedSheetsRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/email-groups': typeof AuthenticatedAdminEmailGroupsRoute
  '/_authenticated/admin/smart-alerts': typeof AuthenticatedAdminSmartAlertsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/agent/inbox': typeof AuthenticatedAgentInboxRoute
  '/_authenticated/alerts/$id': typeof AuthenticatedAlertsIdRoute
  '/_authenticated/sheets/$sheetId': typeof AuthenticatedSheetsSheetIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/agent/': typeof AuthenticatedAgentIndexRoute
  '/_authenticated/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/_authenticated/agent/kpi/$id': typeof AuthenticatedAgentKpiIdRoute
  '/_authenticated/agent/person/$key': typeof AuthenticatedAgentPersonKeyRoute
  '/_authenticated/agent/project/$projectId': typeof AuthenticatedAgentProjectProjectIdRoute
  '/_authenticated/agent/row/$key': typeof AuthenticatedAgentRowKeyRoute
  '/_authenticated/agent/stage/$key': typeof AuthenticatedAgentStageKeyRoute
  '/api/public/hooks/agent-watchers': typeof ApiPublicHooksAgentWatchersRoute
  '/api/public/hooks/concern-nudges': typeof ApiPublicHooksConcernNudgesRoute
  '/api/public/hooks/escalate': typeof ApiPublicHooksEscalateRoute
  '/api/public/hooks/smart-alerts-scan': typeof ApiPublicHooksSmartAlertsScanRoute
  '/api/public/hooks/weekly-briefing': typeof ApiPublicHooksWeeklyBriefingRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agent'
    | '/alerts'
    | '/briefings'
    | '/concerns'
    | '/copilot'
    | '/documents'
    | '/insights'
    | '/my-activities'
    | '/notifications'
    | '/projects'
    | '/search'
    | '/settings'
    | '/sheets'
    | '/email/unsubscribe'
    | '/admin/audit'
    | '/admin/email-groups'
    | '/admin/smart-alerts'
    | '/admin/users'
    | '/agent/inbox'
    | '/alerts/$id'
    | '/sheets/$sheetId'
    | '/lovable/email/suppression'
    | '/agent/'
    | '/alerts/'
    | '/agent/kpi/$id'
    | '/agent/person/$key'
    | '/agent/project/$projectId'
    | '/agent/row/$key'
    | '/agent/stage/$key'
    | '/api/public/hooks/agent-watchers'
    | '/api/public/hooks/concern-nudges'
    | '/api/public/hooks/escalate'
    | '/api/public/hooks/smart-alerts-scan'
    | '/api/public/hooks/weekly-briefing'
    | '/api/public/hooks/weekly-report'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/briefings'
    | '/concerns'
    | '/copilot'
    | '/documents'
    | '/insights'
    | '/my-activities'
    | '/notifications'
    | '/projects'
    | '/search'
    | '/settings'
    | '/sheets'
    | '/email/unsubscribe'
    | '/admin/audit'
    | '/admin/email-groups'
    | '/admin/smart-alerts'
    | '/admin/users'
    | '/agent/inbox'
    | '/alerts/$id'
    | '/sheets/$sheetId'
    | '/lovable/email/suppression'
    | '/agent'
    | '/alerts'
    | '/agent/kpi/$id'
    | '/agent/person/$key'
    | '/agent/project/$projectId'
    | '/agent/row/$key'
    | '/agent/stage/$key'
    | '/api/public/hooks/agent-watchers'
    | '/api/public/hooks/concern-nudges'
    | '/api/public/hooks/escalate'
    | '/api/public/hooks/smart-alerts-scan'
    | '/api/public/hooks/weekly-briefing'
    | '/api/public/hooks/weekly-report'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agent'
    | '/_authenticated/alerts'
    | '/_authenticated/briefings'
    | '/_authenticated/concerns'
    | '/_authenticated/copilot'
    | '/_authenticated/documents'
    | '/_authenticated/insights'
    | '/_authenticated/my-activities'
    | '/_authenticated/notifications'
    | '/_authenticated/projects'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/sheets'
    | '/email/unsubscribe'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/email-groups'
    | '/_authenticated/admin/smart-alerts'
    | '/_authenticated/admin/users'
    | '/_authenticated/agent/inbox'
    | '/_authenticated/alerts/$id'
    | '/_authenticated/sheets/$sheetId'
    | '/lovable/email/suppression'
    | '/_authenticated/agent/'
    | '/_authenticated/alerts/'
    | '/_authenticated/agent/kpi/$id'
    | '/_authenticated/agent/person/$key'
    | '/_authenticated/agent/project/$projectId'
    | '/_authenticated/agent/row/$key'
    | '/_authenticated/agent/stage/$key'
    | '/api/public/hooks/agent-watchers'
    | '/api/public/hooks/concern-nudges'
    | '/api/public/hooks/escalate'
    | '/api/public/hooks/smart-alerts-scan'
    | '/api/public/hooks/weekly-briefing'
    | '/api/public/hooks/weekly-report'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksAgentWatchersRoute: typeof ApiPublicHooksAgentWatchersRoute
  ApiPublicHooksConcernNudgesRoute: typeof ApiPublicHooksConcernNudgesRoute
  ApiPublicHooksEscalateRoute: typeof ApiPublicHooksEscalateRoute
  ApiPublicHooksSmartAlertsScanRoute: typeof ApiPublicHooksSmartAlertsScanRoute
  ApiPublicHooksWeeklyBriefingRoute: typeof ApiPublicHooksWeeklyBriefingRoute
  ApiPublicHooksWeeklyReportRoute: typeof ApiPublicHooksWeeklyReportRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sheets': {
      id: '/_authenticated/sheets'
      path: '/sheets'
      fullPath: '/sheets'
      preLoaderRoute: typeof AuthenticatedSheetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-activities': {
      id: '/_authenticated/my-activities'
      path: '/my-activities'
      fullPath: '/my-activities'
      preLoaderRoute: typeof AuthenticatedMyActivitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/concerns': {
      id: '/_authenticated/concerns'
      path: '/concerns'
      fullPath: '/concerns'
      preLoaderRoute: typeof AuthenticatedConcernsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/briefings': {
      id: '/_authenticated/briefings'
      path: '/briefings'
      fullPath: '/briefings'
      preLoaderRoute: typeof AuthenticatedBriefingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts/': {
      id: '/_authenticated/alerts/'
      path: '/'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AuthenticatedAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedAlertsRoute
    }
    '/_authenticated/agent/': {
      id: '/_authenticated/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AuthenticatedAgentIndexRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sheets/$sheetId': {
      id: '/_authenticated/sheets/$sheetId'
      path: '/$sheetId'
      fullPath: '/sheets/$sheetId'
      preLoaderRoute: typeof AuthenticatedSheetsSheetIdRouteImport
      parentRoute: typeof AuthenticatedSheetsRoute
    }
    '/_authenticated/alerts/$id': {
      id: '/_authenticated/alerts/$id'
      path: '/$id'
      fullPath: '/alerts/$id'
      preLoaderRoute: typeof AuthenticatedAlertsIdRouteImport
      parentRoute: typeof AuthenticatedAlertsRoute
    }
    '/_authenticated/agent/inbox': {
      id: '/_authenticated/agent/inbox'
      path: '/inbox'
      fullPath: '/agent/inbox'
      preLoaderRoute: typeof AuthenticatedAgentInboxRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/smart-alerts': {
      id: '/_authenticated/admin/smart-alerts'
      path: '/admin/smart-alerts'
      fullPath: '/admin/smart-alerts'
      preLoaderRoute: typeof AuthenticatedAdminSmartAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/email-groups': {
      id: '/_authenticated/admin/email-groups'
      path: '/admin/email-groups'
      fullPath: '/admin/email-groups'
      preLoaderRoute: typeof AuthenticatedAdminEmailGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-report': {
      id: '/api/public/hooks/weekly-report'
      path: '/api/public/hooks/weekly-report'
      fullPath: '/api/public/hooks/weekly-report'
      preLoaderRoute: typeof ApiPublicHooksWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-briefing': {
      id: '/api/public/hooks/weekly-briefing'
      path: '/api/public/hooks/weekly-briefing'
      fullPath: '/api/public/hooks/weekly-briefing'
      preLoaderRoute: typeof ApiPublicHooksWeeklyBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/smart-alerts-scan': {
      id: '/api/public/hooks/smart-alerts-scan'
      path: '/api/public/hooks/smart-alerts-scan'
      fullPath: '/api/public/hooks/smart-alerts-scan'
      preLoaderRoute: typeof ApiPublicHooksSmartAlertsScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/escalate': {
      id: '/api/public/hooks/escalate'
      path: '/api/public/hooks/escalate'
      fullPath: '/api/public/hooks/escalate'
      preLoaderRoute: typeof ApiPublicHooksEscalateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/concern-nudges': {
      id: '/api/public/hooks/concern-nudges'
      path: '/api/public/hooks/concern-nudges'
      fullPath: '/api/public/hooks/concern-nudges'
      preLoaderRoute: typeof ApiPublicHooksConcernNudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agent-watchers': {
      id: '/api/public/hooks/agent-watchers'
      path: '/api/public/hooks/agent-watchers'
      fullPath: '/api/public/hooks/agent-watchers'
      preLoaderRoute: typeof ApiPublicHooksAgentWatchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agent/stage/$key': {
      id: '/_authenticated/agent/stage/$key'
      path: '/stage/$key'
      fullPath: '/agent/stage/$key'
      preLoaderRoute: typeof AuthenticatedAgentStageKeyRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/agent/row/$key': {
      id: '/_authenticated/agent/row/$key'
      path: '/row/$key'
      fullPath: '/agent/row/$key'
      preLoaderRoute: typeof AuthenticatedAgentRowKeyRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/agent/project/$projectId': {
      id: '/_authenticated/agent/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/agent/project/$projectId'
      preLoaderRoute: typeof AuthenticatedAgentProjectProjectIdRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/agent/person/$key': {
      id: '/_authenticated/agent/person/$key'
      path: '/person/$key'
      fullPath: '/agent/person/$key'
      preLoaderRoute: typeof AuthenticatedAgentPersonKeyRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/agent/kpi/$id': {
      id: '/_authenticated/agent/kpi/$id'
      path: '/kpi/$id'
      fullPath: '/agent/kpi/$id'
      preLoaderRoute: typeof AuthenticatedAgentKpiIdRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
  }
}

interface AuthenticatedAgentRouteChildren {
  AuthenticatedAgentInboxRoute: typeof AuthenticatedAgentInboxRoute
  AuthenticatedAgentIndexRoute: typeof AuthenticatedAgentIndexRoute
  AuthenticatedAgentKpiIdRoute: typeof AuthenticatedAgentKpiIdRoute
  AuthenticatedAgentPersonKeyRoute: typeof AuthenticatedAgentPersonKeyRoute
  AuthenticatedAgentProjectProjectIdRoute: typeof AuthenticatedAgentProjectProjectIdRoute
  AuthenticatedAgentRowKeyRoute: typeof AuthenticatedAgentRowKeyRoute
  AuthenticatedAgentStageKeyRoute: typeof AuthenticatedAgentStageKeyRoute
}

const AuthenticatedAgentRouteChildren: AuthenticatedAgentRouteChildren = {
  AuthenticatedAgentInboxRoute: AuthenticatedAgentInboxRoute,
  AuthenticatedAgentIndexRoute: AuthenticatedAgentIndexRoute,
  AuthenticatedAgentKpiIdRoute: AuthenticatedAgentKpiIdRoute,
  AuthenticatedAgentPersonKeyRoute: AuthenticatedAgentPersonKeyRoute,
  AuthenticatedAgentProjectProjectIdRoute:
    AuthenticatedAgentProjectProjectIdRoute,
  AuthenticatedAgentRowKeyRoute: AuthenticatedAgentRowKeyRoute,
  AuthenticatedAgentStageKeyRoute: AuthenticatedAgentStageKeyRoute,
}

const AuthenticatedAgentRouteWithChildren =
  AuthenticatedAgentRoute._addFileChildren(AuthenticatedAgentRouteChildren)

interface AuthenticatedAlertsRouteChildren {
  AuthenticatedAlertsIdRoute: typeof AuthenticatedAlertsIdRoute
  AuthenticatedAlertsIndexRoute: typeof AuthenticatedAlertsIndexRoute
}

const AuthenticatedAlertsRouteChildren: AuthenticatedAlertsRouteChildren = {
  AuthenticatedAlertsIdRoute: AuthenticatedAlertsIdRoute,
  AuthenticatedAlertsIndexRoute: AuthenticatedAlertsIndexRoute,
}

const AuthenticatedAlertsRouteWithChildren =
  AuthenticatedAlertsRoute._addFileChildren(AuthenticatedAlertsRouteChildren)

interface AuthenticatedSheetsRouteChildren {
  AuthenticatedSheetsSheetIdRoute: typeof AuthenticatedSheetsSheetIdRoute
}

const AuthenticatedSheetsRouteChildren: AuthenticatedSheetsRouteChildren = {
  AuthenticatedSheetsSheetIdRoute: AuthenticatedSheetsSheetIdRoute,
}

const AuthenticatedSheetsRouteWithChildren =
  AuthenticatedSheetsRoute._addFileChildren(AuthenticatedSheetsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRouteWithChildren
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRouteWithChildren
  AuthenticatedBriefingsRoute: typeof AuthenticatedBriefingsRoute
  AuthenticatedConcernsRoute: typeof AuthenticatedConcernsRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedMyActivitiesRoute: typeof AuthenticatedMyActivitiesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSheetsRoute: typeof AuthenticatedSheetsRouteWithChildren
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminEmailGroupsRoute: typeof AuthenticatedAdminEmailGroupsRoute
  AuthenticatedAdminSmartAlertsRoute: typeof AuthenticatedAdminSmartAlertsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentRoute: AuthenticatedAgentRouteWithChildren,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRouteWithChildren,
  AuthenticatedBriefingsRoute: AuthenticatedBriefingsRoute,
  AuthenticatedConcernsRoute: AuthenticatedConcernsRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedMyActivitiesRoute: AuthenticatedMyActivitiesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSheetsRoute: AuthenticatedSheetsRouteWithChildren,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminEmailGroupsRoute: AuthenticatedAdminEmailGroupsRoute,
  AuthenticatedAdminSmartAlertsRoute: AuthenticatedAdminSmartAlertsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksAgentWatchersRoute: ApiPublicHooksAgentWatchersRoute,
  ApiPublicHooksConcernNudgesRoute: ApiPublicHooksConcernNudgesRoute,
  ApiPublicHooksEscalateRoute: ApiPublicHooksEscalateRoute,
  ApiPublicHooksSmartAlertsScanRoute: ApiPublicHooksSmartAlertsScanRoute,
  ApiPublicHooksWeeklyBriefingRoute: ApiPublicHooksWeeklyBriefingRoute,
  ApiPublicHooksWeeklyReportRoute: ApiPublicHooksWeeklyReportRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
